M48
; DRILL file {KiCad 9.0.6} date 2026-05-11T15:02:08+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-11T15:02:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.850
%
G90
G05
T1
X211.442Y-90.859
X212.458Y-95.939
X213.474Y-90.859
T2
X227.27Y-55.54
X227.27Y-144.44
M30
